spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  docker:
    compose:
      file: src/main/resources/compose.yaml
  flyway:
    clean-on-validation-error: true
    clean-disabled: false
